services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

volumes:
  postgresql_volume:
