"""add uav.noise_characteristics field

Revision ID: 7171c3b2540f
Revises: 97f8ec948683
Create Date: 2024-12-17 16:48:32.208272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7171c3b2540f'
down_revision: Union[str, None] = '97f8ec948683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uav', sa.Column('noise_characteristics', sa.Numeric(), nullable=False))
    op.drop_column('uav', 'number_of_electric_motors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uav', sa.Column('number_of_electric_motors', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('uav', 'noise_characteristics')
    # ### end Alembic commands ###
