"""add fio field

Revision ID: d15b6b91ca94
Revises: 2daa4db8584c
Create Date: 2024-12-03 16:51:36.211669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15b6b91ca94'
down_revision: Union[str, None] = '2daa4db8584c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fio', sa.String(), nullable=False, server_default="Иванов Иван Иванович"))
    op.alter_column('users', 'fio', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fio')
    # ### end Alembic commands ###
