"""add uav flight

Revision ID: 06f8c9928c35
Revises: 54345155864c
Create Date: 2024-12-02 00:55:35.849700

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from uav_service.domain.uav_flight.enums.status_type import UavFlightStatusType


# revision identifiers, used by Alembic.
revision: str = '06f8c9928c35'
down_revision: Union[str, None] = '54345155864c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'uav_flight',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('uav_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum(*map(str, UavFlightStatusType), name='uav_flight_status_type'), nullable=False),
        sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['uav_id'], ['uav.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uav_flight')
    # ### end Alembic commands ###
