"""add uav.reference_number field

Revision ID: 5be225b8c2f3
Revises: 10ad599a0867
Create Date: 2024-12-17 16:35:11.974281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be225b8c2f3'
down_revision: Union[str, None] = '10ad599a0867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uav', sa.Column('reference_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uav', 'reference_number')
    # ### end Alembic commands ###
